### ISSUE TITLE
Payment not confirmed when not returned to webshop

### ISSUE THREAD

**Issue by miviho** [mollie/mollie-odoo#90] opened 2020-10-27 17:24 UTC
Webshop payment is done by iDeal and confirmed by the bank as showed in the browser on the website of the bank before being redirected back to the webshop. When the connection breaks after or during this conform but before being returned to the webshop, the order stays as 'nothing to invoice' and payment is not confirmed in Odoo. 

On the bank account of the customer the payment has been debited. After 90 minutes the status is still unchanged.
On the order it says transaction is started and waiting for confirmation.

Using model 13.0.1.2 on the Odoo.sh V13. 1 database, multiple websites.

**Comment by Yenthe666** [comment] 2020-10-28 08:50
On a sidenote, to add some extra info. This is because of the controller needing to be called from the JS to update the status. If somebody leaves the page early it will mean the JS is not triggering the controller and thus the payment status is not updated.
@odoo-mvds why is there no back-end cron that checks them off later on automatically? :)

**Comment by odoo-mvds** [comment] 2020-10-29 11:27
Hello,

we have tested this but we can't reproduce the issue. Even if we close the window, the webhook is catched correctly it seems. Is there a way we can check your configuration? Are you able to reproduce the issue? If so we would like to see how you reproduce it on your DB.

br,

**Comment by odoo-mvds** [comment] 2020-11-09 19:37
Fixed in v14.0.0.2

**Closed as completed by odoo-mvds** 2020-11-09 19:37 UTC

**Comment by Yenthe666** [comment] 2020-11-10 08:42
Ref https://github.com/mollie/mollie-odoo/commit/b616c403e90174153a6c1c69657d8f0148ab3248 for V14 and https://github.com/mollie/mollie-odoo/commit/5a2fd7abb5b44a99fc2e640b30da92dcf226a0a1 for V13
