### ISSUE TITLE
[12.0] "Pay & Confirm" button from offer does not work

### ISSUE THREAD

**Issue by marcinkuk** [mollie/mollie-odoo#109] opened 2021-05-19 12:03 UTC
I send an offer via e-mail to client.
Client want to confirm and pay an offer but button "Pay & Confirm" does not work.

Odoo version: 12.0
payment_mollie_official version: 12.0.1.5

mollie-api-python==2.2.3
phonenumbers==8.10.19

Any advices?

------------------

![Screen 1](https://user-images.githubusercontent.com/5391645/118808855-38184d80-b8aa-11eb-93ef-bff3f6c443de.png)

**Comment by marcinkuk** [comment] 2021-05-19 12:21
Something from logs:

2021-05-19 12:11:47,603 15 INFO twojdoradca.nl werkzeug: 192.168.1.100 - - [19/May/2021 12:11:47] "GET /web/image/payment.icon/35/image_payment_form?unique=ba0c0b5 HTTP/1.1" 200 - 15 0.004 0.010,
2021-05-19 12:11:47,655 25 INFO twojdoradca.nl werkzeug: 192.168.1.100 - - [19/May/2021 12:11:47] "GET /web/webclient/locale/pl_PL HTTP/1.1" 200 - 1 0.000 0.005,
2021-05-19 12:11:47,657 23 INFO twojdoradca.nl werkzeug: 192.168.1.100 - - [19/May/2021 12:11:47] "GET /web/image/payment.icon/36/image_payment_form?unique=ba0c0b5 HTTP/1.1" 200 - 15 0.005 0.010,
2021-05-19 12:11:47,662 17 INFO twojdoradca.nl werkzeug: 192.168.1.100 - - [19/May/2021 12:11:47] "GET /web/image/payment.icon/38/image_payment_form?unique=ba0c0b5 HTTP/1.1" 200 - 15 0.005 0.010,
2021-05-19 12:11:47,662 14 INFO twojdoradca.nl werkzeug: 192.168.1.100 - - [19/May/2021 12:11:47] "GET /web/image/payment.icon/37/image_payment_form?unique=ba0c0b5 HTTP/1.1" 200 - 15 0.005 0.010,
2021-05-19 12:11:48,094 15 INFO ? werkzeug: 192.168.1.100 - - [19/May/2021 12:11:48] "GET /web/static/lib/fontawesome/fonts/fontawesome-webfont.woff2?v=4.7.0 HTTP/1.1" 200 - - - -,
2021-05-19 12:11:48,165 21 INFO ? werkzeug: 192.168.1.100 - - [19/May/2021 12:11:48] "GET /portal/static/src/xml/portal_chatter.xml HTTP/1.1" 200 - - - -,
2021-05-19 12:11:48,188 17 INFO twojdoradca.nl werkzeug: 192.168.1.100 - - [19/May/2021 12:11:48] "POST /mail/chatter_init HTTP/1.1" 200 - 42 0.023 0.026,
2021-05-19 12:11:48,315 15 INFO ? werkzeug: 192.168.1.100 - - [19/May/2021 12:11:48] "GET /website_mail/static/src/xml/website_mail.xml HTTP/1.1" 200 - - - -,
2021-05-19 12:11:48,426 23 INFO ? werkzeug: 192.168.1.100 - - [19/May/2021 12:11:48] "GET /website_rating/static/src/xml/website_mail.xml HTTP/1.1" 200 - - - -,
2021-05-19 12:11:48,554 21 INFO ? werkzeug: 192.168.1.100 - - [19/May/2021 12:11:48] "GET /web/static/src/img/mimetypes/pdf.svg HTTP/1.1" 200 - - - -,
2021-05-19 12:11:48,566 23 INFO twojdoradca.nl werkzeug: 192.168.1.100 - - [19/May/2021 12:11:48] "GET /web/image/mail.message/124888/author_avatar/50x50 HTTP/1.1" 200 - 11 0.004 0.011,
2021-05-19 12:11:48,570 14 INFO twojdoradca.nl werkzeug: 192.168.1.100 - - [19/May/2021 12:11:48] "GET /web/image/mail.message/124879/author_avatar/50x50 HTTP/1.1" 200 - 11 0.004 0.012,
2021-05-19 12:11:48,597 17 INFO twojdoradca.nl werkzeug: 192.168.1.100 - - [19/May/2021 12:11:48] "GET /web/image/res.partner/4/image_small/50x50 HTTP/1.1" 200 - 19 0.029 0.021,
2021-05-19 12:11:48,982 17 INFO twojdoradca.nl werkzeug: 192.168.1.100 - - [19/May/2021 12:11:48] "GET /web/image/website/1/favicon/ HTTP/1.1" 500 - 5 0.003 0.017,
2021-05-19 12:11:48,992 17 ERROR twojdoradca.nl werkzeug: Error on request:,
Traceback (most recent call last):,
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 205, in run_wsgi,
    execute(self.server.app),
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 193, in execute,
    application_iter = app(environ, start_response),
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 128, in application,
    return application_unproxied(environ, start_response),
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 117, in application_unproxied,
    result = odoo.http.root(environ, start_response),
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1318, in __call__,
    return self.dispatch(environ, start_response),
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1291, in __call__,
    return self.app(environ, start_wrapped),
  File "/usr/lib/python3/dist-packages/werkzeug/wsgi.py", line 599, in __call__,
    return self.app(environ, start_response),
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1486, in dispatch,
    result = ir_http._dispatch(),
  File "/usr/lib/python3/dist-packages/odoo/addons/website_sale/models/ir_http.py", line 15, in _dispatch,
    return super(IrHttp, cls)._dispatch(),
  File "/usr/lib/python3/dist-packages/odoo/addons/auth_signup/models/ir_http.py", line 19, in _dispatch,
    return super(Http, cls)._dispatch(),
  File "/usr/lib/python3/dist-packages/odoo/addons/web_editor/models/ir_http.py", line 22, in _dispatch,
    return super(IrHttp, cls)._dispatch(),
  File "/usr/lib/python3/dist-packages/odoo/addons/http_routing/models/ir_http.py", line 398, in _dispatch,
    result = super(IrHttp, cls)._dispatch(),
  File "/usr/lib/python3/dist-packages/odoo/addons/utm/models/ir_http.py", line 26, in _dispatch,
    response = super(IrHttp, cls)._dispatch(),
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 207, in _dispatch,
    return cls._handle_exception(e),
  File "/usr/lib/python3/dist-packages/odoo/addons/website/models/ir_http.py", line 195, in _handle_exception,
    return super(Http, cls)._handle_exception(exception),
  File "/usr/lib/python3/dist-packages/odoo/addons/utm/models/ir_http.py", line 31, in _handle_exception,
    response = super(IrHttp, cls)._handle_exception(exc),
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 177, in _handle_exception,
    return request._handle_exception(exception),
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 774, in _handle_exception,
    return super(HttpRequest, self)._handle_exception(exception),
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 312, in _handle_exception,
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2]),
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise,
    raise value,
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 203, in _dispatch,
    result = request.dispatch(),
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 833, in dispatch,
    r = self._call_function(**self.params),
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 344, in _call_function,
    return checked_call(self.db, *args, **kwargs),
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper,
    return f(dbname, *args, **kwargs),
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 337, in checked_call,
    result = self.endpoint(*a, **kw),
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 939, in __call__,
    return self.method(*args, **kw),
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 517, in response_wrap,
    response = f(*args, **kw),
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1076, in content_image,
    default_mimetype='image/png', related_id=related_id, access_mode=access_mode, access_token=access_token),
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 435, in binary_content,
    env=env),
  File "/usr/lib/python3/dist-packages/odoo/addons/website/models/ir_http.py", line 317, in binary_content,
    access_mode=access_mode, env=env),
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 365, in binary_content,
    mimetype = guess_mimetype(base64.b64decode(content), default=default_mimetype),
  File "/usr/lib/python3.5/base64.py", line 88, in b64decode,
    return binascii.a2b_base64(s),
binascii.Error: Incorrect padding - - -,

**Comment by odoo-mvds** [comment] 2021-06-01 14:30
Hello,

We cannot reproduce this on our test environment.
See my test on v12 on Odoo.sh: https://drive.google.com/file/d/1avGSPPldhXreJpQD5sZTBp-7T8bo0ut_/view
Can you tell me what hosting you are using. In the past we link this behavior with a bad nginx proxy configuration.
Often the issue is to be found there.

br,

**Comment by marcinkuk** [comment] 2021-06-01 16:30
Hi,

we have two separate odoo instances using the same proxy.

1. First environement
- Odoo v12
- payment_mollie_official version: 12.0.1 (first build probably)
- no multicompany

Result: can buy from site (there is no "buying from an offer" functionality)

2. Second environement
- Odoo v12 (the same build)
- payment_mollie_official version: 12.0.1.5 (newest)
- multicompany

Result: can't buy from site or offer

Summary:
- proxy probably is fine

Questions:
- did you test mollie with multicompany environement?

**Comment by odoo-mvds** [comment] 2021-06-01 16:43
Hi,

Yes it works with multicompanies as well.
I would suggest to update the version in the first environment and check again.

I still think it's the proxy :). Could you share the URL of that website?

br,

**Comment by marcinkuk** [comment] 2021-06-01 16:45
First environement
https://btrb.nl - works

Second environement
https://twojdoradca.nl - doesn't work

**Comment by odoo-mvds** [comment] 2021-06-01 16:48
Could you also install the latest mollie python api please: v2.6.0

**Comment by marcinkuk** [comment] 2021-06-01 16:55
> Could you also install the latest mollie python api please: v2.6.0

mollie-api-python==2.6.0 installed, container restarted

**Comment by odoo-mvds** [comment] 2021-06-01 16:57
ok, you can send me an offer to odoo@applix.be?

**Comment by marcinkuk** [comment] 2021-06-01 17:00
> ok, you can send me an offer to [odoo@applix.be](mailto:odoo@applix.be)?

The offer sent.

You can check the same behaviour by buying from our website:
https://twojdoradca.nl/shop

**Comment by odoo-mvds** [comment] 2021-06-01 17:07
could you check in system parameters that your base URL includes HTTPS. It seems this isn't the case.

**Comment by marcinkuk** [comment] 2021-06-01 17:10
> could you check in system parameters that your base URL includes HTTPS. It seems this isn't the case.

web.base.url	https://twojdoradca.nl
web.base.url.freeze	True

**Comment by odoo-mvds** [comment] 2021-06-01 17:13
it's not what i'm seeing: 

&lt;meta property="og:url" content="http://twojdoradca.nl/"/&gt;
--
&nbsp; | &nbsp;
&nbsp; | &lt;meta property="og:description" content="Twój doradca w Holandii."/&gt;
&nbsp; | &nbsp;
&nbsp; | &lt;meta property="og:site_name" content="Additional Solution"/&gt;
&nbsp; | &nbsp;
&nbsp; | &lt;meta property="og:type" content="website"/&gt;
&nbsp; | &nbsp;
&nbsp; | &lt;meta property="og:title" content="Twojdoradca.nl"/&gt;
&nbsp; | &nbsp;
&nbsp; | &lt;meta property="og:image" content="http://twojdoradca.nl/web/image/res.company/1/logo"/&gt;

I think this could also be a settings in nginx.

**Comment by marcinkuk** [comment] 2021-06-01 17:19
I don't know where I could check or change.

We had http://twojdoradca.nl in company description.
I changed to https://twojdoradca.nl

Could you check now?
Where can I check these properties?

**Comment by marcinkuk** [comment] 2021-06-01 17:33
In other environement we have similar situation:

Site: https://btrb.nl/shop

meta property="og:site_name" content="bTRB.nl"/>
meta property="og:type" content="website"/>
meta property="og:title" content="Payment | bTRB"/>
meta property="og:image" content="http://btrb.nl/web/image/res.company/1/logo"/>
meta property="og:url" content="http://btrb.nl/shop/payment"/>

but older mollie version works.

**Comment by odoo-mvds** [comment] 2021-06-02 09:04
Hello,

After further analysis, we found that the version that is used of this website is very old.
Methods that gives the errors in the console is added 2 years ago by Odoo. So we expect that your version is too old.
Is it possible to upgrade Odoo 12 to a more recent build?

thanks,

**Comment by odoo-mvds** [comment] 2021-06-03 09:00
Hello,

Do you have any feedback?

thanks!

**Comment by marcinkuk** [comment] 2021-06-03 09:14
Yes. We are trying upgrade odoo v12 to the latest build.
We have some troubles to resolve.
We will let you know when we do.

**Comment by odoo-mvds** [comment] 2021-06-30 12:51
Closing issue as no feedback in 27 days.

**Closed as completed** 2021-06-30 12:50 UTC

**Comment by marcinkuk** [comment] 2021-08-27 09:19
Hi,

sorry for the delay.
We had to update odoo to the latest build and fix "https" issue.

The problem still exist.
Clicking "Pay and Confirm" button doesn't nothing.

Odoo 12.0-20210809
Mollie Payments	12.0.1.6
Metadata in html with https

Can you help me?
