### ISSUE TITLE
[13.0] Payment status update bug

### ISSUE THREAD

**Issue by PCatinean** [mollie/mollie-odoo#81] opened 2020-08-18 17:04 UTC
When I have a payment, where the confirmation from mollie doesn't come instantly (e.g. due to technical reasons or because it's a sepa transfer which take several days) the status of the payment doesn't change in Odoo. I think it is because in the V13 of the mollie module there is no webhook transmitted to mollie.

It seems the code for v12 and at v13 are missing this part.

**Comment by odoo-mvds** [comment] 2020-09-22 08:32
This is fixed in the new update.
Webhooks are supported now and so this issue is fixed.

**Closed as completed by odoo-mvds** 2020-09-22 08:32 UTC

**Comment by miviho** [comment] 2020-10-27 16:31
Using model 13.0.1.2 on the Odoo.sh V13.

Looks like there is still something wrong.

Webshop payment is done by iDeal and confirmed by the bank as showed in the browser on the website of the bank before being redirected back to the webshop. When the connection breaks after or during this conform but before being returned to the webshop, the order stays as 'nothing to invoice' and payment is not conformed in Odoo. On the back account of the customer the payment has been debited. After 30 minutes the status has not been changed.

**Comment by odoo-mvds** [comment] 2020-10-27 16:50
Hello,

Can you see if the payment trigger is visible in the SO? At the right you should be able to see this:
![image](https://user-images.githubusercontent.com/59664044/97333276-aef0e900-187b-11eb-8d9c-fc9cedf80f44.png)

thanks,

**Comment by miviho** [comment] 2020-10-27 16:51
Yes it is there

**Comment by miviho** [comment] 2020-10-27 16:51
![image](https://user-images.githubusercontent.com/59970288/97334437-0ba0d380-187d-11eb-8c27-0e4dc00f22d5.png)

**Comment by odoo-mvds** [comment] 2020-10-27 17:04
Are you using multiple databases on the same URL?

**Comment by miviho** [comment] 2020-10-27 17:08
One db and multiple website. Mollie is configured with mentioning the website.

**Comment by odoo-mvds** [comment] 2020-10-27 17:11
please create a new ticket here. Then we will look further into your issue. This ticket is closed.
