### ISSUE TITLE
Error while installing v13

### ISSUE THREAD

**Issue by tsteenbergen96** [mollie/mollie-odoo#42] opened 2019-11-19 14:31 UTC
I got an error when I try to install Odoo Mollie v13 connector. The python packages are installed and the Odoo service/server has restart. I don't what I am doing wrong but it won't install. Anyone who could help?
Thanks!

Odoo Server Error
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/tools/convert.py", line 713, in parse
    self._tag_root(de)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 675, in _tag_root
    f(rec)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 675, in _tag_root
    f(rec)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 578, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/odoo/odoo-server/odoo/models.py", line 4045, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/odoo/odoo-server/odoo/models.py", line 3959, in _load_records_create
    return self.create(values)
  File "<decorator-gen-178>", line 2, in create
  File "/odoo/odoo-server/odoo/api.py", line 325, in _model_create_single
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/odoo/odoo-server/odoo/api.py", line 325, in <genexpr>
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/odoo/odoo-server/addons/payment_transfer/models/payment.py", line 60, in create
    return super(TransferPaymentAcquirer, self).create(values)
  File "<decorator-gen-169>", line 2, in create
  File "/odoo/odoo-server/odoo/api.py", line 322, in _model_create_single
    return create(self, arg)
  File "/odoo/odoo-server/addons/payment/models/payment_acquirer.py", line 304, in create
    record = super(PaymentAcquirer, self).create(vals)
  File "<decorator-gen-3>", line 2, in create
  File "/odoo/odoo-server/odoo/api.py", line 343, in _model_create_multi
    return create(self, [arg])
  File "/odoo/odoo-server/odoo/models.py", line 3664, in create
    raise ValueError("Invalid field %r on model %r" % (key, self._name))
ValueError: Invalid field 'image' on model 'payment.acquirer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/odoo/odoo-server/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 909, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 1323, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 1311, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 395, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 382, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-58>", line 2, in button_immediate_install
  File "/odoo/odoo-server/odoo/addons/base/models/ir_module.py", line 72, in check_and_log
    return method(self, *args, **kwargs)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_module.py", line 463, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_module.py", line 573, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/odoo/odoo-server/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 420, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 312, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/odoo/odoo-server/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 737, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 804, in convert_xml_import
    obj.parse(doc.getroot())
  File "/odoo/odoo-server/odoo/tools/convert.py", line 722, in parse
    exc_info[2]
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 13, in reraise
    raise value.with_traceback(tb)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 713, in parse
    self._tag_root(de)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 675, in _tag_root
    f(rec)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 675, in _tag_root
    f(rec)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 578, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/odoo/odoo-server/odoo/models.py", line 4045, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/odoo/odoo-server/odoo/models.py", line 3959, in _load_records_create
    return self.create(values)
  File "<decorator-gen-178>", line 2, in create
  File "/odoo/odoo-server/odoo/api.py", line 325, in _model_create_single
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/odoo/odoo-server/odoo/api.py", line 325, in <genexpr>
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/odoo/odoo-server/addons/payment_transfer/models/payment.py", line 60, in create
    return super(TransferPaymentAcquirer, self).create(values)
  File "<decorator-gen-169>", line 2, in create
  File "/odoo/odoo-server/odoo/api.py", line 322, in _model_create_single
    return create(self, arg)
  File "/odoo/odoo-server/addons/payment/models/payment_acquirer.py", line 304, in create
    record = super(PaymentAcquirer, self).create(vals)
  File "<decorator-gen-3>", line 2, in create
  File "/odoo/odoo-server/odoo/api.py", line 343, in _model_create_multi
    return create(self, [arg])
  File "/odoo/odoo-server/odoo/models.py", line 3664, in create
    raise ValueError("Invalid field %r on model %r" % (key, self._name))
odoo.tools.convert.ParseError: "Invalid field 'image' on model 'payment.acquirer'" while parsing /odoo/custom/addons/payment_mollie_official/data/payment_acquirer_data.xml:2, near
<odoo>
    <data>
        </data>
    <data noupdate="1">
        <record id="payment_acquirer_mollie" model="payment.acquirer">
            <field name="name">Mollie</field>
            <field name="image" type="base64" file="payment_mollie_official/static/src/img/mollie_icon.png"/>
            <field name="provider">mollie</field>
            <field name="company_id" ref="base.main_company"/>
            <field name="view_template_id" ref="payment_mollie_official.mollie_form"/>
            <field name="environment">test</field>
            <field name="dashboard_url">https://www.mollie.com/dashboard</field>
            <field name="pre_msg">
&lt;p&gt;You will be redirected to the Mollie website after clicking on payment button.&lt;/p&gt;</field>
            <field name="mollie_api_key_test">mollie api test key</field>
            <field name="mollie_api_key_prod">mollie api live key</field>
            <field name="module_id" ref="base.module_payment_mollie_official"/>
            <field name="description" type="html">
                <p>
                    A payment gateway to accept online payments via various payment methods (check https://www.mollie.com/be/payments/).
                </p>
                <ul>
                    <li><i class="fa fa-check"/>eCommerce</li>
                </ul>
            </field>
        </record>
    </data>
</odoo>

**Comment by tsteenbergen96** [comment] 2019-11-21 12:22
Anyone who can help with fixing this? @Yenthe666

**Comment by Yenthe666** [comment] 2019-11-22 09:24
I've left the company that was working on this. @ploegvde and @bizzappdevteam are now responsible for this project.

**Comment by goodvines** [comment] 2019-11-22 16:05
Same here, I get the same error message. @ploegvde @bizzappdevteam

**Comment by tsteenbergen96** [comment] 2019-11-23 21:55
> Same here, I get the same error message. @ploegvde @bizzappdevteam

"Glad" I am not the only one :) 

Looking forward to get a reply from the developers!

**Comment by ploegvde** [comment] 2019-11-25 16:42
The V13 is not yet final. The 13.0 branch should not have been created. Version 13 is expected soon. WE will update this issue when V13 is ready.

**Comment by tsteenbergen96** [comment] 2019-11-25 17:09
Thanks for letting us know @ploegvde. Any idea of a release date? Is it in like a few days, a couple of months?

**Comment by goodvines** [comment] 2019-11-25 17:10
Thanks for that information. I got a different from one of your staff on the website chat saying it's already working based on the instructions in this branch. Any timeframe for a stable release?

**Comment by BusinessAgilityMasters** [comment] 2019-12-16 10:52
Is there an update on this, would like to use Mollie on Odoo13

**Comment by Alliance-IT** [comment] 2019-12-31 11:47
Same, is there an update regarding Odoo v13 and Mollie?

**Comment by codeagencybe** [comment] 2020-01-04 15:55
Any update yet? Odoo v13 is now available for 3+ months. 
This update could be have been available much sooner...

**Comment by ghost** [comment] 2020-01-20 13:06
Version 13 is released and can be used. If you find any issues please raise a new github issue.

**Comment by codeagencybe** [comment] 2020-01-20 23:57
@odooexpertsbv 

Where can I download the new release? 
On apps.odoo.com there is no official v13 package yet for downloading. 
Also, here in repo branch 13.0, it shows last commit 8 days, I don't think that is the latest release is it since you just posted update 11 hours ago? 
The release tab only shows 2 files, both from 2017. 

Can you please kindly update the correct source?

**Comment by Yenthe666** [comment] 2020-01-21 07:09
@codeagencybe that's because Mollie itself didn't add the 13.0 app on the appstore yet probably. I'm pretty sure that the 13.0 branch is the latest and stable 13.0 version (https://github.com/mollie/mollie-odoo/tree/13.0)
@odooexpertsbv thanks for the release 🎈

**Comment by codeagencybe** [comment] 2020-01-21 07:46
@Yenthe666 Yes since v13, Odoo applies new rules it seems. Anything from v13 and upwards will always be a seperate sale as from v12 and downwards, a purchase always included all versions. 
Hopefully Mollie can can add that app also asap as most non-developer people will probably miss out on the newest version as they don't know to checkout on Github. 

Regarding the latest release; 
I found the 13.0 branch but what confuses me is that the last commit was 8 days ago while their announcement was just 19 hours ago. 
I had a chat with Mollie support to report that v13 was missing out just last week, which is less than 8 days ago. 
They confirmed me they are still working on it -> which is AFTER that commit from 8 days ago. 
So that's the part that is confusing. 
In the chat, Mollie itself is referring to a PR that is still waiting due to conflicts. 
This one: https://github.com/mollie/mollie-odoo/pull/43

Enclosed screenshots from my communication with Mollie. 

So form this point of view, that was my concern wether or not the release from 8 days ago is now ok or not or if still something is waiting. 

![image](https://user-images.githubusercontent.com/7568546/72784838-0fd2fd00-3c2a-11ea-8a5d-cdc06ba1abd6.png)
 
![image](https://user-images.githubusercontent.com/7568546/72784993-693b2c00-3c2a-11ea-8154-802d67d9d1ec.png)

**Comment by Yenthe666** [comment] 2020-01-21 08:17
Hmm I think there's quite some miscommunication between the Odoo partner, Mollie and their support team then honestly. I don't see why they'd want PR 43 in before it being 'available' but there are some things in 43 that should probably land in 13 :) All in all: too many parties involved and too little communication probably.

**Comment by ghost** [comment] 2020-02-18 18:11
There should be no problem in installing version 13. Version 13 is not on the Odoo App store at the moment, but that is a technical issue. You  can pull the lates V13 from the repo and install the module in Odoo. I will close this issue. If a problem is still there, please raise a new issue with all relevant info to reproduce the issue. Cheers.

**Closed as completed by ghost** 2020-02-18 18:11 UTC

**Comment by wilfriedsip** [comment] 2020-02-18 19:58
still have the same problem.
Did all what the Readme is saying.

Fout:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/tools/convert.py", line 713, in parse
    self._tag_root(de)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 675, in _tag_root
    f(rec)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 675, in _tag_root
    f(rec)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 578, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/odoo/odoo-server/odoo/models.py", line 4067, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/odoo/odoo-server/odoo/models.py", line 3981, in _load_records_create
    return self.create(values)
  File "<decorator-gen-187>", line 2, in create
  File "/odoo/odoo-server/odoo/api.py", line 325, in _model_create_single
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/odoo/odoo-server/odoo/api.py", line 325, in <genexpr>
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/odoo/odoo-server/addons/payment_transfer/models/payment.py", line 60, in create
    return super(TransferPaymentAcquirer, self).create(values)
  File "<decorator-gen-179>", line 2, in create
  File "/odoo/odoo-server/odoo/api.py", line 322, in _model_create_single
    return create(self, arg)
  File "/odoo/odoo-server/addons/payment/models/payment_acquirer.py", line 304, in create
    record = super(PaymentAcquirer, self).create(vals)
  File "<decorator-gen-3>", line 2, in create
  File "/odoo/odoo-server/odoo/api.py", line 343, in _model_create_multi
    return create(self, [arg])
  File "/odoo/odoo-server/odoo/models.py", line 3686, in create
    raise ValueError("Invalid field %r on model %r" % (key, self._name))
ValueError: Invalid field 'image' on model 'payment.acquirer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/odoo/odoo-server/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 910, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 1324, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 1312, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 395, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 382, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-58>", line 2, in button_immediate_install
  File "/odoo/odoo-server/odoo/addons/base/models/ir_module.py", line 72, in check_and_log
    return method(self, *args, **kwargs)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_module.py", line 463, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_module.py", line 573, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/odoo/odoo-server/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 420, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 312, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/odoo/odoo-server/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 737, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 804, in convert_xml_import
    obj.parse(doc.getroot())
  File "/odoo/odoo-server/odoo/tools/convert.py", line 722, in parse
    exc_info[2]
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 13, in reraise
    raise value.with_traceback(tb)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 713, in parse
    self._tag_root(de)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 675, in _tag_root
    f(rec)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 675, in _tag_root
    f(rec)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 578, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/odoo/odoo-server/odoo/models.py", line 4067, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/odoo/odoo-server/odoo/models.py", line 3981, in _load_records_create
    return self.create(values)
  File "<decorator-gen-187>", line 2, in create
  File "/odoo/odoo-server/odoo/api.py", line 325, in _model_create_single
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/odoo/odoo-server/odoo/api.py", line 325, in <genexpr>
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/odoo/odoo-server/addons/payment_transfer/models/payment.py", line 60, in create
    return super(TransferPaymentAcquirer, self).create(values)
  File "<decorator-gen-179>", line 2, in create
  File "/odoo/odoo-server/odoo/api.py", line 322, in _model_create_single
    return create(self, arg)
  File "/odoo/odoo-server/addons/payment/models/payment_acquirer.py", line 304, in create
    record = super(PaymentAcquirer, self).create(vals)
  File "<decorator-gen-3>", line 2, in create
  File "/odoo/odoo-server/odoo/api.py", line 343, in _model_create_multi
    return create(self, [arg])
  File "/odoo/odoo-server/odoo/models.py", line 3686, in create
    raise ValueError("Invalid field %r on model %r" % (key, self._name))
odoo.tools.convert.ParseError: "Invalid field 'image' on model 'payment.acquirer'" while parsing /odoo/custom/addons/payment_mollie_official/data/payment_acquirer_data.xml:2, near
<odoo>
    <data>
        </data>
    <data noupdate="1">
        <record id="payment_acquirer_mollie" model="payment.acquirer">
            <field name="name">Mollie</field>
            <field name="image" type="base64" file="payment_mollie_official/static/src/img/mollie_icon.png"/>
            <field name="provider">mollie</field>
            <field name="company_id" ref="base.main_company"/>
            <field name="view_template_id" ref="payment_mollie_official.mollie_form"/>
            <field name="pre_msg">
&lt;p&gt;You will be redirected to the Mollie website after clicking on the payment button.&lt;/p&gt;</field>
            <field name="mollie_api_key_test">mollie api test key</field>
            <field name="mollie_api_key_prod">mollie api live key</field>
            <field name="module_id" ref="base.module_payment_mollie_official"/>
            <field name="description" type="html">
                <p>
                    A payment gateway to accept online payments via various payment methods (check https://www.mollie.com/be/payments/).
                </p>
                <ul>
                    <li><i class="fa fa-check"/>eCommerce</li>
                </ul>
            </field>
        </record>
    </data>
</odoo>

**Comment by ghost** [comment] 2020-02-19 06:57
Hello @wilfriedsip  seems like you have still master branch of mollie-odoo. Please checkout the 13.0 branch and it should be working without any error.

**Comment by Yenthe666** [comment] 2020-02-19 07:11
@odooexpertsbv I noticed more people doing this actually. Maybe the default branch can be set to 13.0? That should avoid some confusion/mistakes 😃

**Comment by wilfriedsip** [comment] 2020-02-19 08:28
@odooexpertsbv, Thank you for let me know. You are totally correct.
After the 13.0 branch everything works. thank you
